name: Prescription WorkFlow

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Network
        run: docker network create inside
      - name: Build the stack
        run: docker-compose up